import pandas as pd

# Load the CSV file
file_path = 'datasets/physionet.org/files/ptb-xl/1.0.3/ptbxl_database.csv'
df = pd.read_csv(file_path)

# Drop the specified columns
columns_to_drop = ['nurse', 'site', 'validated_by', 'second_opinion', 'initial_autogenerated_report', 'validated_by_human']
df = df.drop(columns=columns_to_drop)

# Replace missing values in the specified columns with null (NaN)
columns_to_fill_null = [
    'baseline_drift', 'burst_noise', 'electrodes_problems',
    'extra_beats', 'pacemaker', 'heart_axis',
    'infarction_stadium1', 'infarction_stadium2'
]
df[columns_to_fill_null] = df[columns_to_fill_null].fillna(pd.NA)

# Save the cleaned file back to the same location or a new file
cleaned_file_path = 'datasets/physionet.org/files/ptb-xl/1.0.3/ptbxl_database_cleaned.csv'
df.to_csv(cleaned_file_path, index=False)

print(f"Cleaned file saved to {cleaned_file_path}")